import type { ApplicationState } from "./application-state.js";
import type { CoverLetterArtifact, ResumeArtifact } from "./artifacts.js";
import type {
  AutomationApprovalLog,
  AutomationPreferences,
  AutomationSuggestion,
} from "./automation.js";
import type { Opportunity } from "./opportunity.js";
import { CONTRACT_VERSION } from "./primitives.js";
import type { Insight } from "./insights.js";
import type {
  CareerStrategySummary,
  CrossTrackStrategyComparison,
  StrategyConfidence,
  SearchTrackStrategySummary,
} from "./strategy.js";
import type { CompassEvaluation } from "./compass-evaluation.js";
import type { Workspace } from "./workspace.js";

const now = "2026-05-13T18:00:00.000Z";
const userId = "11111111-1111-4111-8111-111111111111";
const workspaceId = "22222222-2222-4222-8222-222222222222";
const opportunityId = "33333333-3333-4333-8333-333333333333";
const evaluationId = "44444444-4444-4444-8444-444444444444";
const resumeArtifactId = "55555555-5555-4555-8555-555555555555";
const coverLetterArtifactId = "66666666-6666-4666-8666-666666666666";
const applicationStateId = "77777777-7777-4777-8777-777777777777";
const automationSuggestionId = "12121212-1212-4212-8212-121212121212";
const automationApprovalLogId = "13131313-1313-4313-8313-131313131313";
const automationPreferencesId = "14141414-1414-4414-8414-141414141414";
const insightId = "15151515-1515-4515-8515-151515151515";

const strategyConfidence: StrategyConfidence = {
  confidence: "weak",
  basis: "Based on stored opportunities, applications, COMPASS evaluations, and artifact performance records.",
  sampleSize: 3,
  sourceInputs: { opportunities: 3, applications: 2, compassEvaluations: 2 },
  knownUncertainty: ["Outcome history is still thin."],
  insufficientData: [],
  userOverrides: null,
};

export const workspaceExample: Workspace = {
  contractVersion: CONTRACT_VERSION,
  id: workspaceId,
  userId,
  title: "Full-time leadership search",
  description: "Search for senior engineering leadership roles.",
  workspaceType: "full_time_leadership",
  status: "active",
  preferences: {
    targetTitles: ["Director of Engineering", "VP Engineering"],
    targetSeniority: ["director", "executive"],
    preferredRemoteTypes: ["remote", "hybrid"],
    preferredLocations: ["Chicago", "Remote US"],
    targetCompensation: {
      min: 180000,
      max: 240000,
      currency: "USD",
      period: "annual",
      sourceText: "$180k-$240k annual",
    },
    targetKeywords: ["platform", "engineering leadership", "AI"],
    avoidKeywords: ["commission only"],
    notes: "Prioritize credible product and platform teams.",
  },
  aiContextSummary: "Candidate is targeting engineering leadership roles.",
  tags: ["leadership", "full-time"],
  metadata: {},
  createdAt: now,
  updatedAt: now,
  archivedAt: null,
};

export const opportunityExample: Opportunity = {
  contractVersion: CONTRACT_VERSION,
  id: opportunityId,
  workspaceId,
  sourceType: "linkedin_manual",
  sourceUrl: "https://example.com/jobs/123",
  rawContent: "Example Systems is hiring a Senior Platform Engineering Manager...",
  normalizedContent: {
    description: "Lead platform engineering teams and improve delivery systems.",
    responsibilities: ["Lead platform teams", "Improve engineering delivery"],
    requirements: ["Engineering management", "Cloud platforms"],
    skills: ["Python", "PostgreSQL", "AWS"],
    seniority: "senior",
    notes: "Parsed from manually supplied job posting content.",
  },
  company: {
    name: "Example Systems",
    websiteUrl: "https://example.com",
    industry: "SaaS",
    notes: null,
  },
  title: "Senior Platform Engineering Manager",
  employmentType: "full_time",
  compensation: {
    min: 170000,
    max: 220000,
    currency: "USD",
    period: "annual",
    sourceText: "$170k-$220k",
  },
  location: {
    label: "Chicago, IL",
    city: "Chicago",
    region: "IL",
    country: "US",
    timezone: "America/Chicago",
  },
  remoteMode: "hybrid",
  parseConfidence: { title: 0.96, company: 0.94 },
  tags: ["platform", "leadership"],
  status: "interested",
  metadata: {},
  createdAt: now,
  updatedAt: now,
};

export const compassEvaluationExample: CompassEvaluation = {
  contractVersion: CONTRACT_VERSION,
  id: evaluationId,
  workspaceId,
  opportunityId,
  version: {
    version: "compass_evaluation_v1",
    previousVersion: null,
    changeReason: "Initial canonical evaluation contract.",
  },
  status: "completed",
  modelMetadata: {
    provider: "openai",
    model: "gpt-5-mini",
    promptVersion: "compass_prompt_v1",
    rulesetVersion: "compass_rules_v1",
    inputTokenEstimate: 1800,
    outputTokenEstimate: 900,
    latencyMs: 1200,
  },
  summary: "The opportunity appears directionally aligned with platform leadership goals.",
  overallScore: 78,
  strengths: [{ label: "Leadership alignment", score: 0.82, evidence: ["Lead platform teams"], notes: null }],
  gaps: [{ label: "Company risk", score: 0.4, evidence: [], notes: "Limited company context supplied." }],
  risks: [{ label: "Hybrid requirement", score: 0.3, evidence: ["Chicago hybrid"], notes: null }],
  atsFindings: {
    matchedKeywords: ["platform", "PostgreSQL"],
    missingKeywords: ["AI strategy"],
    keywordNotes: "Keyword coverage is partial.",
    score: 72,
  },
  compensationFindings: {
    status: "aligned",
    notes: "Posted range overlaps target compensation.",
    evidence: ["$170k-$220k"],
    score: 80,
  },
  recommendations: {
    decision: "apply",
    rationale: "The role has enough alignment to justify applying after review.",
    nextActions: ["Review hybrid expectations", "Tailor resume to platform leadership"],
  },
  confidence: {
    level: "medium",
    score: 0.72,
    rationale: "Role and compensation data are available, but company context is limited.",
  },
  sections: {
    strategicFit: { status: "strong_match", score: 82, summary: "Aligned to platform leadership.", evidence: ["Lead platform teams"], gaps: [], assumptions: [] },
    technicalAlignment: { status: "partial_match", score: 72, summary: "Core technical themes are present.", evidence: ["Python", "PostgreSQL"], gaps: ["AI strategy"], assumptions: [] },
    seniorityAlignment: { status: "strong_match", score: 84, summary: "Management seniority appears aligned.", evidence: ["Engineering Manager"], gaps: [], assumptions: [] },
    compensationAlignment: { status: "strong_match", score: 80, summary: "Range overlaps target.", evidence: ["$170k-$220k"], gaps: [], assumptions: [] },
    remoteAlignment: { status: "partial_match", score: 65, summary: "Hybrid may need review.", evidence: ["Chicago hybrid"], gaps: [], assumptions: [] },
    companyRisk: { status: "insufficient_data", score: null, summary: "Limited company details supplied.", evidence: [], gaps: ["No company research yet"], assumptions: [] },
    applicationEffort: { status: "partial_match", score: 70, summary: "Likely requires focused tailoring.", evidence: [], gaps: [], assumptions: [] },
    atsResumeAlignment: { status: "partial_match", score: 72, summary: "Some keyword alignment.", evidence: ["platform", "PostgreSQL"], gaps: ["AI strategy"], assumptions: [] },
  },
  assumptions: ["No external research was used."],
  reproducibility: {
    inputHash: "sha256:evaluation-input",
    roleContentHash: "sha256:role-content",
    sourceHash: "sha256:resume-source",
    promptVersion: "compass_prompt_v1",
    rulesetVersion: "compass_rules_v1",
    sourceHashes: { resume: "sha256:resume-source" },
    deterministicBaseline: { score: 78 },
  },
  metadata: {},
  createdAt: now,
  updatedAt: now,
};

export const resumeArtifactExample: ResumeArtifact = {
  contractVersion: CONTRACT_VERSION,
  id: resumeArtifactId,
  workspaceId,
  opportunityId,
  sourceArtifactId: null,
  artifactType: "tailored_resume",
  lifecycleStatus: "draft",
  title: "Example Systems tailored resume",
  content: "Resume content prepared for Example Systems.",
  formatMetadata: {
    primaryFormat: "md",
    availableFormats: ["md", "pdf", "docx"],
    contentHash: "sha256:resume-artifact",
  },
  generationMetadata: {
    generatedBy: "ai",
    modelMetadata: compassEvaluationExample.modelMetadata,
    promptVersion: "resume_artifact_prompt_v1",
    inputHash: "sha256:resume-input",
    groundingSourceIds: [],
    warnings: [],
  },
  exportMetadata: [{ format: "pdf", exportedAt: null, fileName: null, contentHash: null }],
  revision: {
    revisionId: "88888888-8888-4888-8888-888888888888",
    parentArtifactId: null,
    revisionNumber: 1,
    changeSummary: "Initial tailored resume artifact.",
    createdAt: now,
  },
  uploadMetadata: null,
  parsingMetadata: null,
  tailoringNotes: "Emphasize platform leadership.",
  reviewedAt: null,
  submittedAt: null,
  archivedAt: null,
  metadata: {},
  createdAt: now,
  updatedAt: now,
};

export const coverLetterArtifactExample: CoverLetterArtifact = {
  contractVersion: CONTRACT_VERSION,
  id: coverLetterArtifactId,
  workspaceId,
  opportunityId,
  sourceArtifactId: null,
  artifactType: "cover_letter",
  lifecycleStatus: "draft",
  title: "Example Systems cover letter",
  content: "Cover letter content prepared for Example Systems.",
  tone: "direct",
  generationMetadata: {
    generatedBy: "ai",
    modelMetadata: compassEvaluationExample.modelMetadata,
    promptVersion: "cover_letter_prompt_v1",
    inputHash: "sha256:cover-letter-input",
    groundingSourceIds: [],
    warnings: [],
  },
  editHistory: [{ editedAt: now, editedBy: "user", summary: "Reviewed opening paragraph." }],
  exportMetadata: [{ format: "docx", exportedAt: null, fileName: null, contentHash: null }],
  revision: {
    revisionId: "99999999-9999-4999-8999-999999999999",
    parentArtifactId: null,
    revisionNumber: 1,
    changeSummary: "Initial cover letter artifact.",
    createdAt: now,
  },
  reviewedAt: null,
  submittedAt: null,
  archivedAt: null,
  metadata: {},
  createdAt: now,
  updatedAt: now,
};

export const applicationStateExample: ApplicationState = {
  contractVersion: CONTRACT_VERSION,
  id: applicationStateId,
  workspaceId,
  opportunityId,
  currentState: "interested",
  stateHistory: [
    {
      state: "discovered",
      changedAt: now,
      changedBy: "user",
      reason: "Opportunity pasted into Careero.",
      metadata: {},
    },
    {
      state: "interested",
      changedAt: now,
      changedBy: "user",
      reason: "COMPASS baseline recommended applying.",
      metadata: {},
    },
  ],
  reminders: [
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      dueAt: "2026-05-20T15:00:00.000Z",
      title: "Decide whether to apply",
      notes: null,
      completedAt: null,
    },
  ],
  notes: [
    {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      createdAt: now,
      author: "Local User",
      body: "Review hybrid expectations before applying.",
    },
  ],
  interviewStages: [
    {
      id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
      stageType: "recruiter_screen",
      title: "Recruiter screen",
      scheduledAt: "2026-05-22T16:00:00.000Z",
      completedAt: null,
      status: "scheduled",
      interviewerNames: ["Recruiter One"],
      locationOrMeetingLink: "Video",
      notes: "Discuss role scope and hybrid expectations.",
      preparationNotes: "Review role scope and hybrid expectations.",
      outcomeNotes: null,
      metadata: {},
    },
  ],
  externalLinks: [{ label: "Job posting", url: "https://example.com/jobs/123", type: "posting" }],
  metadata: {},
  createdAt: now,
  updatedAt: now,
};

export const automationSuggestionExample: AutomationSuggestion = {
  contractVersion: CONTRACT_VERSION,
  id: automationSuggestionId,
  workspaceId,
  targetType: "application",
  targetId: applicationStateId,
  opportunityId,
  applicationId: applicationStateId,
  artifactId: null,
  actionType: "follow_up_suggestion",
  title: "Review follow-up timing",
  summary: "This application has been applied for more than seven days without a recorded response.",
  reason: "A gentle follow-up may be useful if the user still wants to pursue the opportunity.",
  basis: "Application applied date is older than the workspace follow-up threshold and no interview or offer is recorded.",
  confidence: "Weak Signal",
  sourceInputs: { appliedAt: "2026-05-01T15:00:00.000Z", thresholdDays: 7 },
  preview: {
    title: "Draft follow-up note",
    body: "Consider checking whether a short, professional follow-up is appropriate.",
    contentHash: "sha256:automation-preview",
    externalMutation: false,
  },
  status: "active",
  expiresAt: null,
  policyVersion: "automation_policy_v1",
  metadata: {},
  createdAt: now,
  updatedAt: now,
};

export const automationApprovalLogExample: AutomationApprovalLog = {
  contractVersion: CONTRACT_VERSION,
  id: automationApprovalLogId,
  workspaceId,
  suggestionId: automationSuggestionId,
  actor: "user",
  targetType: "application",
  targetId: applicationStateId,
  actionType: "follow_up_suggestion",
  preview: automationSuggestionExample.preview,
  previewHash: "sha256:automation-preview",
  approvalStatus: "approved",
  dismissalOrRejectionReason: null,
  executionStatus: "not_applicable",
  executionResult: {},
  externalMutation: false,
  policyVersion: "automation_policy_v1",
  createdAt: now,
  decidedAt: now,
  executedAt: null,
};

export const automationPreferencesExample: AutomationPreferences = {
  contractVersion: CONTRACT_VERSION,
  id: automationPreferencesId,
  workspaceId,
  enabled: true,
  suggestionCategories: [
    "follow_up_suggestion",
    "reminder_suggestion",
    "artifact_readiness_check",
    "communication_draft",
    "workflow_state_suggestion",
    "opportunity_review_suggestion",
    "future_external_action_disabled",
  ],
  followUpSuggestionDays: 7,
  artifactReadinessChecksEnabled: true,
  communicationDraftsEnabled: true,
  internalStateChangeSuggestionsEnabled: true,
  futureExternalActionsEnabled: false,
  quietMode: false,
  policyVersion: "automation_policy_v1",
  metadata: {},
  createdAt: now,
  updatedAt: now,
};

export const insightExamples: Insight[] = [
  {
    contractVersion: CONTRACT_VERSION,
    id: insightId,
    category: "fit_alignment",
    label: "Opportunity fit is directionally positive",
    message: "This opportunity has enough stored alignment to justify focused review.",
    basis: "Uses the latest COMPASS evaluation and reviewed opportunity fields.",
    confidence: "Moderate Confidence",
    confidenceLevel: "moderate",
    confidenceExplanation: "COMPASS and opportunity fields are present, but outcome history is thin.",
    knownUncertainty: ["No external company research was included."],
    warnings: [],
    severity: "positive",
    priority: 60,
    generationMethod: "deterministic",
    visibility: "internal",
    scope: {
      userScoped: true,
      workspaceId,
      opportunityId,
      compassEvaluationId: evaluationId,
      artifactId: null,
      applicationId: applicationStateId,
    },
    sourceReferences: [
      {
        sourceType: "opportunity",
        sourceId: opportunityId,
        label: "Saved opportunity",
        field: null,
        metadata: {},
      },
      {
        sourceType: "compass_evaluation",
        sourceId: evaluationId,
        label: "Latest COMPASS evaluation",
        field: "overallScore",
        metadata: {},
      },
    ],
    sourceInputs: { overallScore: 78, recommendation: "apply" },
    freshness: {
      generatedAt: now,
      sourceUpdatedAt: now,
      isStale: false,
      refreshReason: null,
    },
    recommendedAction: {
      actionType: "review_opportunity",
      label: "Review opportunity detail",
      routePath: `/opportunities/${opportunityId}/overview`,
      reviewRequired: false,
      metadata: {},
    },
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
  {
    contractVersion: CONTRACT_VERSION,
    id: "15151515-1515-4515-8515-151515151516",
    category: "search_track_strategy",
    label: "Search track evidence is still thin",
    message: "Strategy guidance should be treated as directional until more outcomes are tracked.",
    basis: "Counts stored opportunities, applications, and completed COMPASS evaluations.",
    confidence: "Insufficient Data",
    confidenceLevel: "insufficient_data",
    confidenceExplanation: "Only a small number of outcomes are available.",
    knownUncertainty: ["Small samples can change quickly."],
    warnings: ["This is not external market data."],
    severity: "info",
    priority: null,
    generationMethod: "deterministic",
    visibility: "internal",
    scope: {
      userScoped: true,
      workspaceId,
      opportunityId: null,
      compassEvaluationId: null,
      artifactId: null,
      applicationId: null,
    },
    sourceReferences: [{ sourceType: "workspace", sourceId: workspaceId, label: "Search track", field: null, metadata: {} }],
    sourceInputs: { opportunities: 3, applications: 2 },
    freshness: { generatedAt: now, sourceUpdatedAt: now, isStale: false, refreshReason: null },
    recommendedAction: null,
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
  {
    contractVersion: CONTRACT_VERSION,
    id: "15151515-1515-4515-8515-151515151517",
    category: "compass",
    label: "COMPASS sample is thin",
    message: "Search-level COMPASS direction is still a weak signal.",
    basis: "Fewer than three completed COMPASS scores are available.",
    confidence: "Insufficient Data",
    confidenceLevel: "insufficient_data",
    confidenceExplanation: "Completed COMPASS evaluations are below the recommended sample size.",
    knownUncertainty: ["One new evaluation can materially change the trend."],
    warnings: [],
    severity: "info",
    priority: null,
    generationMethod: "deterministic",
    visibility: "internal",
    scope: {
      userScoped: true,
      workspaceId,
      opportunityId: null,
      compassEvaluationId: null,
      artifactId: null,
      applicationId: null,
    },
    sourceReferences: [],
    sourceInputs: { scoreCount: 1 },
    freshness: { generatedAt: now, sourceUpdatedAt: now, isStale: false, refreshReason: null },
    recommendedAction: null,
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
  {
    contractVersion: CONTRACT_VERSION,
    id: "15151515-1515-4515-8515-151515151518",
    category: "risk_red_flag",
    label: "Possible sustainability risk",
    message: "Multiple saved roles include high-pressure language.",
    basis: "Matches cautionary phrasing in reviewed job descriptions.",
    confidence: "Weak Signal",
    confidenceLevel: "weak",
    confidenceExplanation: "Phrase matching is advisory and may need user review.",
    knownUncertainty: ["Job descriptions can exaggerate or omit operating reality."],
    warnings: ["Review manually before deprioritizing any opportunity."],
    severity: "caution",
    priority: 50,
    generationMethod: "deterministic",
    visibility: "internal",
    scope: {
      userScoped: true,
      workspaceId,
      opportunityId,
      compassEvaluationId: null,
      artifactId: null,
      applicationId: null,
    },
    sourceReferences: [{ sourceType: "raw_job_description", sourceId: opportunityId, label: "Raw job description", field: "rawContent", metadata: {} }],
    sourceInputs: { matchedPhrases: ["high pressure"] },
    freshness: { generatedAt: now, sourceUpdatedAt: now, isStale: false, refreshReason: null },
    recommendedAction: null,
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
  {
    contractVersion: CONTRACT_VERSION,
    id: "15151515-1515-4515-8515-151515151519",
    category: "follow_up_action",
    label: "Review follow-up timing",
    message: "This application has been applied for more than seven days without a recorded response.",
    basis: "Application applied date is older than the follow-up threshold and no interview or offer is recorded.",
    confidence: "Weak Signal",
    confidenceLevel: "weak",
    confidenceExplanation: "Follow-up timing depends on user preference and the posting process.",
    knownUncertainty: ["Careero cannot see external recruiter inboxes."],
    warnings: [],
    severity: "info",
    priority: 40,
    generationMethod: "deterministic",
    visibility: "internal",
    scope: {
      userScoped: true,
      workspaceId,
      opportunityId,
      compassEvaluationId: null,
      artifactId: null,
      applicationId: applicationStateId,
    },
    sourceReferences: [{ sourceType: "application_event", sourceId: applicationStateId, label: "Application workflow", field: "appliedAt", metadata: {} }],
    sourceInputs: { thresholdDays: 7 },
    freshness: { generatedAt: now, sourceUpdatedAt: now, isStale: false, refreshReason: null },
    recommendedAction: {
      actionType: "review_follow_up",
      label: "Review follow-up",
      routePath: `/applications/${applicationStateId}/overview`,
      reviewRequired: true,
      metadata: {},
    },
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
];

export const insightExample: Insight = insightExamples[0];

export const searchTrackStrategySummaryExample: SearchTrackStrategySummary = {
  contractVersion: CONTRACT_VERSION,
  workspaceId,
  workspaceName: "Full-time leadership search",
  generatedAt: now,
  summary:
    "Based on your stored Careero data, this search track has early fit signals but limited outcome evidence.",
  basis:
    "Derived from local workspace opportunities, application workflow states, latest COMPASS evaluations, compensation observations, source intelligence, historical learning, and artifact performance records.",
  confidence: strategyConfidence,
  sampleSize: {
    opportunities: 3,
    applications: 2,
    submittedApplications: 1,
    responses: 1,
    compassEvaluations: 2,
    artifactPerformanceRecords: 1,
  },
  sourceInputs: {
    analytics: "/api/analytics/search",
    compass: "/api/analytics/compass",
    compensation: "/api/analytics/compensation",
  },
  knownUncertainty: ["This is not external market data."],
  insufficientData: [],
  signals: [
    {
      id: "compass-fit",
      category: "compass",
      label: "High-fit opportunities are producing traction",
      message:
        "At least one higher-fit opportunity has a stored interview or offer signal.",
      basis: "Latest COMPASS scores and application workflow outcomes.",
      severity: "positive",
      confidence: strategyConfidence,
      sourceInputs: { highFitOpportunities: 1 },
    },
  ],
  compensationAlignment: {
    summary:
      "Stored stated compensation partially overlaps the workspace target. This is an internal comparison only.",
    basis:
      "Compares saved opportunity compensation ranges with workspace target compensation.",
    confidence: strategyConfidence,
    observations: [{ statedRanges: 2 }],
  },
  skillGapThemes: [],
  roleMarketPositioning: {
    summary:
      "Saved roles appear concentrated around leadership and platform themes in this workspace.",
    basis:
      "Uses title-derived categories and repeated COMPASS alignment patterns from stored opportunities.",
    confidence: strategyConfidence,
    themes: ["leadership", "platform"],
  },
  careerNarrativeThemes: [],
  retrospective: {
    summary:
      "The track has enough stored evidence for directional review, but not enough for strong conclusions.",
    basis: "Combines stored opportunities, applications, COMPASS results, and outcomes.",
    confidence: strategyConfidence,
    notes: ["No external market data was used."],
  },
  actionCandidates: [
    {
      id: "review-compensation-target",
      category: "review_compensation_target",
      title: "Review compensation target",
      rationale:
        "Some saved opportunities state compensation below the workspace target.",
      basis: "Stored stated compensation compared with workspace preferences.",
      confidence: strategyConfidence,
      sourceInputs: { underTarget: 1 },
      advisoryOnly: true,
    },
  ],
  warnings: ["Strategy synthesis is read-only and advisory."],
};

export const crossTrackStrategyComparisonExample: CrossTrackStrategyComparison = {
  generatedAt: now,
  basis: "Compares read-only derived summaries across local workspaces.",
  confidence: strategyConfidence,
  tracks: [
    {
      workspaceId,
      workspaceName: "Full-time leadership search",
      summary: "Early evidence is directional but thin.",
      sampleSize: searchTrackStrategySummaryExample.sampleSize,
      signalCount: 1,
      warningCount: 1,
    },
  ],
  signals: [],
  insufficientData: [],
  warnings: ["Cross-track comparison uses internal Careero data only."],
};

export const careerStrategySummaryExample: CareerStrategySummary = {
  contractVersion: CONTRACT_VERSION,
  generatedAt: now,
  summary: "One search track has a read-only strategy summary available.",
  workspaceId,
  workspaceName: "Full-time leadership search",
  activeTrack: searchTrackStrategySummaryExample,
  tracks: [searchTrackStrategySummaryExample],
  crossTrackComparison: crossTrackStrategyComparisonExample,
  warnings: ["No strategy records are persisted by this response model."],
};

export const canonicalExamples = {
  Workspace: workspaceExample,
  Opportunity: opportunityExample,
  CompassEvaluation: compassEvaluationExample,
  Insight: insightExample,
  ResumeArtifact: resumeArtifactExample,
  CoverLetterArtifact: coverLetterArtifactExample,
  ApplicationState: applicationStateExample,
  AutomationSuggestion: automationSuggestionExample,
  AutomationApprovalLog: automationApprovalLogExample,
  AutomationPreferences: automationPreferencesExample,
  SearchTrackStrategySummary: searchTrackStrategySummaryExample,
  CrossTrackStrategyComparison: crossTrackStrategyComparisonExample,
  CareerStrategySummary: careerStrategySummaryExample,
} as const;
